import React, { useState, useEffect, useRef } from 'react';
import { ChatInput } from './components/ChatInput';
import { MessageBubble } from './components/MessageBubble';
import { ModeSelector } from './components/ModeSelector';
import { DisclaimerModal } from './components/DisclaimerModal';
import { generateResponse } from './services/geminiService';
import { ChatMode, Message, UserLocation, Attachment } from './types';
import { Activity, Trash2, Download, CheckCircle, Cloud, FileText } from 'lucide-react';

const STORAGE_KEY = 'dr_gemini_chat_history';

const App: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [currentMode, setCurrentMode] = useState<ChatMode>(ChatMode.CONSULTATION);
  const [hasAcceptedDisclaimer, setHasAcceptedDisclaimer] = useState(false);
  const [userLocation, setUserLocation] = useState<UserLocation | undefined>(undefined);
  const [showSaveToast, setShowSaveToast] = useState(false);
  const [isAutoSaved, setIsAutoSaved] = useState(false);
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Load history from local storage on mount
  useEffect(() => {
    const savedMessages = localStorage.getItem(STORAGE_KEY);
    if (savedMessages) {
        try {
            const parsed = JSON.parse(savedMessages);
            // Convert string timestamps back to Date objects
            const hydrated = parsed.map((m: any) => ({
                ...m,
                timestamp: new Date(m.timestamp)
            }));
            setMessages(hydrated);
        } catch (e) {
            console.error("Failed to load chat history", e);
        }
    }
  }, []);

  // Auto-save history to local storage
  useEffect(() => {
      if (messages.length > 0) {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(messages));
        
        // Trigger visual auto-save indicator
        setIsAutoSaved(true);
        const timer = setTimeout(() => setIsAutoSaved(false), 2000);
        return () => clearTimeout(timer);
      }
  }, [messages]);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Get location on mount
  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setUserLocation({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
          });
        },
        (error) => {
          console.log("Location access denied or error:", error);
        }
      );
    }
  }, []);

  const clearHistory = () => {
      if (window.confirm("Are you sure you want to clear your medical consultation history?")) {
          setMessages([]);
          localStorage.removeItem(STORAGE_KEY);
      }
  };

  const handleDownloadReport = () => {
    if (messages.length === 0) return;
    
    let content = `MEDICAL CONSULTATION REPORT - Dr. AI\n`;
    content += `Generated on: ${new Date().toLocaleString()}\n`;
    content += `----------------------------------------------------------\n\n`;
    
    messages.forEach(msg => {
      const role = msg.role === 'user' ? 'PATIENT' : 'Dr. AI';
      const time = msg.timestamp.toLocaleTimeString();
      const modeText = msg.mode ? `[Mode: ${msg.mode}]` : '';
      
      content += `${time} - ${role} ${modeText}:\n`;
      content += `${msg.text}\n`;
      
      if (msg.attachments && msg.attachments.length > 0) {
          content += `(Patient provided ${msg.attachments.length} visual attachment(s))\n`;
      }
      content += `\n`;
    });
    
    content += `----------------------------------------------------------\n`;
    content += `DISCLAIMER: This document was generated by Dr. AI, an artificial intelligence assistant. \n`;
    content += `It is provided for informational purposes only and is NOT a substitute for professional medical advice, diagnosis, or treatment. \n`;
    content += `Please present this summary to your primary care physician or a licensed healthcare professional.\n\n`;
    content += `Platform developed by: Muhammad Aneeq Ur Rehman\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Dr_AI_Medical_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setShowSaveToast(true);
    setTimeout(() => setShowSaveToast(false), 3000);
  };

  const handleSendMessage = async (text: string, attachments: Attachment[] = []) => {
    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      text,
      timestamp: new Date(),
      mode: currentMode,
      attachments: attachments
    };

    setMessages((prev) => [...prev, userMessage]);
    setIsLoading(true);

    try {
      const tempId = (Date.now() + 1).toString();
      
      if (currentMode === ChatMode.CONSULTATION) {
          setMessages(prev => [...prev, {
              id: tempId,
              role: 'model',
              text: '',
              timestamp: new Date(),
              mode: currentMode,
              isThinking: true
          }]);
      }

      // Convert history to format required by service
      const historyPayload = messages.map(m => {
          const parts: any[] = [];
          
          if (m.attachments) {
              m.attachments.forEach(a => {
                  parts.push({
                      inlineData: {
                          mimeType: a.mimeType,
                          data: a.data
                      }
                  });
              });
          }
          
          if (m.text) {
              parts.push({ text: m.text });
          }
          
          return {
              role: m.role,
              parts: parts
          };
      });

      const response = await generateResponse({
        prompt: text,
        history: historyPayload,
        mode: currentMode,
        location: userLocation,
        attachments: attachments
      });
      
      if (currentMode === ChatMode.CONSULTATION) {
          setMessages(prev => prev.map(m => 
              m.id === tempId 
              ? { ...m, text: response.text, isThinking: false, groundingMetadata: response.groundingMetadata }
              : m
          ));
      } else {
          const botMessage: Message = {
            id: Date.now().toString(),
            role: 'model',
            text: response.text,
            timestamp: new Date(),
            mode: currentMode,
            groundingMetadata: response.groundingMetadata
          };
          setMessages((prev) => [...prev, botMessage]);
      }
      
    } catch (error) {
      console.error(error);
      const errorMessage: Message = {
        id: Date.now().toString(),
        role: 'model',
        text: "I apologize, but I'm having trouble connecting to the medical database. Please try again.",
        timestamp: new Date(),
        mode: currentMode,
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-50 relative">
      
      {!hasAcceptedDisclaimer && (
        <DisclaimerModal onAccept={() => setHasAcceptedDisclaimer(true)} />
      )}

      {/* Toast Notification */}
      <div className={`fixed top-20 right-6 z-50 transform transition-all duration-300 ${showSaveToast ? 'translate-y-0 opacity-100' : '-translate-y-4 opacity-0 pointer-events-none'}`}>
          <div className="bg-emerald-600 text-white px-4 py-2 rounded-lg shadow-lg flex items-center gap-2 font-medium text-sm">
              <CheckCircle className="w-4 h-4" />
              Report Downloaded Successfully
          </div>
      </div>

      {/* Header */}
      <header className="bg-white px-6 py-4 border-b border-slate-200 flex items-center justify-between shadow-sm z-20">
        <div className="flex items-center gap-3">
          <div className="bg-blue-600 p-2 rounded-lg text-white">
            <Activity className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-800 tracking-tight">Dr. AI</h1>
            <div className="flex items-center gap-2">
               <div className="flex items-center gap-1.5">
                   <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                   <p className="text-xs text-slate-500 font-medium">Dr. AI is Online</p>
               </div>
               
               {/* Auto-save Indicator */}
               <div className={`flex items-center gap-1 transition-opacity duration-500 ${isAutoSaved ? 'opacity-100' : 'opacity-0'}`}>
                   <span className="text-slate-300">|</span>
                   <Cloud className="w-3 h-3 text-slate-400" />
                   <span className="text-[10px] text-slate-400 font-medium">Auto-saved</span>
               </div>
            </div>
          </div>
        </div>
        
        {messages.length > 0 && (
            <div className="flex items-center gap-1">
                <button 
                    onClick={handleDownloadReport}
                    className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors flex items-center gap-2"
                    title="Download Consultation Report"
                >
                    <Download className="w-5 h-5" />
                    <span className="hidden md:inline text-xs font-semibold">Download Report</span>
                </button>
                <div className="w-px h-6 bg-slate-200 mx-1"></div>
                <button 
                    onClick={clearHistory}
                    className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                    title="Clear Consultation History"
                >
                    <Trash2 className="w-5 h-5" />
                </button>
            </div>
        )}
      </header>

      {/* Mode Selector */}
      <ModeSelector 
        currentMode={currentMode} 
        onModeChange={setCurrentMode} 
        disabled={isLoading} 
      />

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto p-4 md:p-6 scrollbar-hide">
        <div className="max-w-4xl mx-auto min-h-full flex flex-col justify-end">
          {messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center text-center text-slate-400 my-auto py-20 opacity-0 animate-in fade-in slide-in-from-bottom-4 duration-700 fill-mode-forwards">
               <div className="w-20 h-20 bg-blue-50 rounded-full flex items-center justify-center mb-6 shadow-sm border border-blue-100">
                 <Activity className="w-10 h-10 text-blue-400" />
               </div>
               <h3 className="text-lg font-semibold text-slate-600 mb-2">Hello, I am Dr. AI.</h3>
               <p className="max-w-md mx-auto mb-8">
                 I am here to help. Describe your symptoms, ask about treatments, or find specialists nearby.
               </p>
               
               <div className="grid grid-cols-1 md:grid-cols-2 gap-4 w-full max-w-lg">
                   <button onClick={() => handleSendMessage("I have a persistent headache and sensitivity to light.")} className="p-4 bg-white border border-slate-200 rounded-xl hover:border-blue-300 hover:shadow-md transition-all text-sm text-left group">
                       <span className="block font-semibold text-slate-700 mb-1 group-hover:text-blue-600">Symptom Check</span>
                       "I have a headache and sensitivity to light..."
                   </button>
                   <button onClick={() => {
                       setCurrentMode(ChatMode.FIND_CARE);
                       handleSendMessage("Find a cardiologist near me who accepts new patients.");
                   }} className="p-4 bg-white border border-slate-200 rounded-xl hover:border-emerald-300 hover:shadow-md transition-all text-sm text-left group">
                       <span className="block font-semibold text-slate-700 mb-1 group-hover:text-emerald-600">Find a Specialist</span>
                       "Find a cardiologist near me..."
                   </button>
               </div>
            </div>
          ) : (
            messages.map((msg) => (
              <MessageBubble key={msg.id} message={msg} />
            ))
          )}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input Area */}
      <ChatInput 
        onSendMessage={handleSendMessage} 
        isLoading={isLoading} 
        activeMode={currentMode}
      />
      
    </div>
  );
};

export default App;