import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import { Message, AuthUser } from '../types';

export const exportToTXT = (messages: Message[], user: AuthUser | null) => {
  let content = `Dr. AI - Medical Report\n\n`;
  content += `Patient: ${user?.name || 'Anonymous'}\n`;
  content += `Generated On: ${new Date().toLocaleString()}\n\n`;
  content += `--- Consultation Transcript ---\n\n`;

  messages.forEach((msg) => {
    const role = msg.role === 'user' ? 'Patient' : 'Dr. AI';
    content += `${role} (${new Date(msg.timestamp).toLocaleTimeString()}):\n`;
    content += `${msg.text}\n\n`;
  });

  content += `DISCLAIMER: This report is generated by AI for informational purposes only. Consultation with a doctor is necessary.\n`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `Dr_AI_Report_${user?.name?.replace(/\s+/g, '_') || 'Patient'}.txt`);
};

export const exportToPDF = (messages: Message[], user: AuthUser | null) => {
  const patientName = user?.name || "Anonymous";
  
  // @ts-ignore
  const doc = new jsPDF();
  const reportId = `DR-AI-${Math.random().toString(36).substring(2, 9).toUpperCase()}`;
  const date = new Date().toLocaleString();

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text("Dr. AI - Medical Report", 20, 25);
  
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  doc.text(`Report ID: ${reportId}`, 150, 50);
  doc.text(`Generated On: ${date}`, 150, 55);

  doc.setFontSize(14);
  doc.text("Patient Information", 20, 70);
  doc.setDrawColor(226, 232, 240);
  doc.line(20, 72, 190, 72);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(`Name: ${patientName}`, 25, 82);
  doc.text(`Mode: ${messages[messages.length-1]?.mode || 'N/A'}`, 25, 89);

  let yPos = 110;

  const lastAiMsg = [...messages].reverse().find(m => m.role === 'model');
  if (lastAiMsg) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text("Recommended Actions & Summary", 20, yPos);
    doc.line(20, yPos + 2, 190, yPos + 2);
    yPos += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const summaryText = lastAiMsg.text.replace(/\*\*/g, '').replace(/\*/g, '');
    const splitSummary = doc.splitTextToSize(summaryText, 160);
    doc.text(splitSummary, 25, yPos);
    yPos += (splitSummary.length * 6) + 15;
  }

  if (yPos > 240) {
    doc.addPage();
    yPos = 25;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text("Consultation Transcript", 20, yPos);
  doc.line(20, yPos + 2, 190, yPos + 2);
  yPos += 15;

  messages.forEach((msg) => {
    if (yPos > 260) {
      doc.addPage();
      yPos = 25;
    }
    
    const role = msg.role === 'user' ? 'Patient' : 'Dr. AI';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text(`${role} (${new Date(msg.timestamp).toLocaleTimeString()}):`, 25, yPos);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 41, 59);
    const splitText = doc.splitTextToSize(msg.text, 160);
    doc.text(splitText, 25, yPos + 6);
    yPos += (splitText.length * 6) + 12;
  });

  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  const disclaimerHeight = doc.internal.pageSize.height - 15;
  doc.text("DISCLAIMER: This report is generated by AI for informational purposes only.", 20, disclaimerHeight);
  
  doc.save(`Dr_AI_Report_${patientName.replace(/\s+/g, '_')}.pdf`);
};

export const exportToDOCX = async (messages: Message[], user: AuthUser | null) => {
  const patientName = user?.name || "Anonymous";
  const dateStr = new Date().toLocaleString();

  const children = [
    new Paragraph({
      text: "Dr. AI - Medical Report",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      text: `Patient: ${patientName}`,
      heading: HeadingLevel.HEADING_2,
    }),
    new Paragraph({
      text: `Generated On: ${dateStr}`,
    }),
    new Paragraph({ text: "" }),
    new Paragraph({
      text: "Consultation Transcript",
      heading: HeadingLevel.HEADING_1,
    }),
  ];

  messages.forEach(msg => {
    const role = msg.role === 'user' ? 'Patient' : 'Dr. AI';
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${role} (${new Date(msg.timestamp).toLocaleTimeString()}):`,
            bold: true,
            color: "475569",
          }),
        ],
        spacing: { before: 200, after: 100 },
      }),
      new Paragraph({
        text: msg.text,
      })
    );
  });

  children.push(
    new Paragraph({ text: "" }),
    new Paragraph({
      children: [
        new TextRun({
          text: "DISCLAIMER: This report is generated by AI for informational purposes only. Consultation with a doctor is necessary.",
          italics: true,
          color: "94A3B8"
        })
      ]
    })
  );

  const doc = new Document({
    sections: [{
      properties: {},
      children: children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `Dr_AI_Report_${patientName.replace(/\s+/g, '_')}.docx`);
};
